pipeline {
  agent any

  stages {

    stage('Clone') {
      steps {
        git 'https://github.com/your-repo/project.git'
      }
    }

    stage('Build Images') {
      steps {
        sh '''
        docker build -t service-a ./service-a
        docker build -t service-b ./service-b
        docker build -t service-c ./service-c
        '''
      }
    }

    stage('Import to K3s') {
      steps {
        sh '''
        docker save service-a | sudo k3s ctr images import -
        docker save service-b | sudo k3s ctr images import -
        docker save service-c | sudo k3s ctr images import -
        '''
      }
    }

    stage('Deploy') {
      steps {
        sh 'kubectl apply -f k8s/'
      }
    }
  }
}
